const API_BASE_URL_DEVELOPMENT = 'https://localhost:7073';
const API_BASE_URL_PRODUCTION = 'https://appname.azurewebsites.net';

const  ENDPOINTS = {
    GET_ALL_POSTS: '/api/Tasks', //id user
    CREATE_POST: '/api/Tasks',
    UPDATE_POST: '/api/Tasks',
    DELETE_POST_BY_ID: '/api/Tasks', // -by-id 
    REGISTER_USER: '/api/Users/register',
    LOGIN: '/api/Users/login'
};

const DEVELOPMENT = {
    API_URL_GET_ALL_POSTS: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.GET_ALL_POSTS}`,
    API_URL_CREATE_POST: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.CREATE_POST}`,
    API_URL_UPDATE_POST: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.UPDATE_POST}`,
    API_URL_DELETE_POST_BY_ID: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.DELETE_POST_BY_ID}`,
    API_URL_REGISTER: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.REGISTER_USER}`,
    API_URL_LOGIN: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.LOGIN}`
};

const PRODUCTION = {
    API_URL_GET_ALL_POSTS: `${API_BASE_URL_PRODUCTION}${ENDPOINTS.GET_ALL_POSTS}`,
    API_URL_CREATE_POST: `${API_BASE_URL_PRODUCTION}${ENDPOINTS.CREATE_POST}`,
    API_URL_UPDATE_POST: `${API_BASE_URL_PRODUCTION}${ENDPOINTS.UPDATE_POST}`,
    API_URL_DELETE_POST_BY_ID: `${API_BASE_URL_PRODUCTION}${ENDPOINTS.DELETE_POST_BY_ID}`,
    API_URL_REGISTER: `${API_BASE_URL_PRODUCTION}${ENDPOINTS.REGISTER_USER}`,
    API_URL_LOGIN: `${API_BASE_URL_PRODUCTION}${ENDPOINTS.LOGIN}`
};

const Costants = process.env.NODE_ENV === 'development' ? DEVELOPMENT : PRODUCTION;

export default Costants; 